#!/bin/bash
# Compares our pipeline's writeback.out to the writeback.out
# generated by the project 3 pipeline
# Prints results to test_results.out

echo "Cleaning up before running tests..."
make nuke

w_ans="test_progs/correct_writeback"
p_ans="test_progs/correct_program"
failed="FALSE"

touch test_results.out
echo "Beginning tests..."
echo "		RUNNING SYNTHESIS TEST SUITE" > test_results.out
echo "" >> test_results.out

for file in test_progs/*.s; do
	w_failed="FALSE"
	p_failed="FALSE"
	file=$(echo $file | cut -d'.' -f1)
	file=$(echo $file | cut -d'/' -f2)

	echo "Assembling $file..."
	make SOURCE="test_progs/$file.s" assembly

	echo "Running $file..."
	make syn

	echo "Verifying writeback.out result for $file..."
	diff $w_ans/$file.writeback.out writeback.out > $file.writeback.diff.out
	if [ -s $file.writeback.diff.out ]; then
		echo "Failed $file writeback.out check!"
		w_failed="TRUE"
		failed="TRUE"
	else
		echo "Passed $file writeback.out check!"
	fi
	rm $file.writeback.diff.out

	echo "Verifying program.out result for $file..."
	grep '@@@' syn_program.out > program.out
	diff $p_ans/$file.program.out program.out > $file.program.diff.out
	if [ -s $file.program.diff.out ]; then
		echo "Failed $file program.out check!"
		p_failed="TRUE"
		failed="TRUE"
	else
		echo "Passed $file program.out check!"
	fi
	rm $file.program.diff.out

	echo "Saving $file test result to test_results.out"
	if [ "$w_failed" == "FALSE" ]; then
		if [ "$p_failed" == "FALSE" ]; then
			echo "Passed $file" >> test_results.out
		else
			echo "Failed $file  ---  correct writeback.out,   incorrect program.out" >> test_results.out
		fi
	else
		if [ "$p_failed" == "FALSE" ]; then
			echo "Failed $file  ---  incorrect writeback.out, correct program.out" >> test_results.out
		else
			echo "Failed $file  ---  incorrect writeback.out, incorrect program.out" >> test_results.out
		fi
	fi
done

echo ""
if [ "$failed" == "FALSE" ]; then
    echo "PASSED SYNTHESIS TEST SUITE"
    echo "		PASSED SYNTHESIS TEST SUITE" >> test_results.out
else
    echo "FAILED SYNTHESIS TEST SUITE"
    echo "		FAILED SYNTHESIS TEST SUITE" >> test_results.out
fi